"""changes in foods table

Revision ID: ba60de17e175
Revises: 239f534d1bde
Create Date: 2025-04-05 19:53:02.292301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba60de17e175'
down_revision: Union[str, None] = '239f534d1bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foods', sa.Column(' vitamin_c', sa.Float(), nullable=False))
    op.add_column('foods', sa.Column('calcium', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('foods', 'calcium')
    op.drop_column('foods', ' vitamin_c')
    # ### end Alembic commands ###
